### ISSUE TITLE
Formatting the data on linux

### ISSUE THREAD

**Issue by azpoliak** [azpoliak/skip-gram-tensor#3]
As noted at https://github.com/azpoliak/skip-gram-tensor/issues/2#issuecomment-360751191, `w2.sub` directory is empty when running `make-embeddings.sh`. This needs to be further debugged.

**Comment by alexanderpanchenko** [comment]
Hello, 

I've tested on a small dataset the toolkit on my mac and it works fine. Thanks! 
However, we need to run it on a linux machine as one person in our lab wants to try it and he does not have a mac (and also the input data are large so running it on a laptop is difficult). Can you please look again into the issue?

**Comment by azpoliak** [comment]
Check out the most recent commit: d437ab849d13b6ae9b12ec32215c861eca597a47.  In `make-embeddings.sh`, I removed the sub-sampling command line for `scripts/corpus2pairs.py` and it now generates the appropriate files when I run it on a linux.

**Comment by azpoliak** [comment]
@alexanderpanchenko, lmk if that fixes it on your Linux machine and if so please close the issue

**Comment by alexanderpanchenko** [comment]
thanks, it worked. just with a small catch:

```
(base) panchenko@ltnode1b:~/skip-gram-tensor/hyperref-tensor$ bash make-embeddings.sh
rm -rf word2vec word2phrase distance word-analogy compute-accuracy count_and_filter word2vecf word2vec3
gcc word2vec.c -o word2vec -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result
gcc word2phrase.c -o word2phrase -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result
gcc distance.c -o distance -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result
In file included from distance.c:19:0:
malloc.h:28:29: fatal error: mach/mach_types.h: No such file or directory
compilation terminated.
makefile:19: recipe for target 'distance' failed
make: *** [distance] Error 1

```

I needed to commend some jobs due to the mentioned above error to make it work:

![image](https://user-images.githubusercontent.com/1456830/35814476-6d9010c6-0a96-11e8-81c1-144ae95ee9a2.png)

**Comment by alexanderpanchenko** [comment]
I think the issue can be closed (I cannot do it myself).

**Comment by alexanderpanchenko** [comment]
The system here is Ubuntu 16.04.

**Comment by azpoliak** [comment]
There's an issue with malloc.h. On a mac one has to include the .h file in
the same directory and then access it in a file via "malloc.h". On a Linux,
one uses <malloc.h>. I'm not sure what's the best option to keep in this
repo. I'm sure there's an elegant solution to this online somewhere.

**Comment by alexanderpanchenko** [comment]
not sure either (maybe making a IFDEF darwin can solve it...)

**Comment by azpoliak** [comment]
Thanks for the suggestion! I'll add it as an eventual todo for the repo.
