### ISSUE TITLE
docopt not working

### ISSUE THREAD

**Issue by adamlauretig** [azpoliak/skip-gram-tensor#4]
This looks really cool, and I'm exciting to work with it, but unfortunately, I'm running into the following error:

Docopt exists on my computer, but when I run the following

`
make clean;make

# Download corpus. We chose a small corpus for the example, and larger corpora will yield better results.
#wget http://www.statmt.org/wmt14/training-monolingual-news-crawl/news.2010.en.shuffled.gz
#gzip -d news.2010.en.shuffled.gz
#CORPUS=news.2010.en.shuffled
#wget http://mattmahoney.net/dc/text8.zip
#unzip text8.zip
#CORPUS=text8
CORPUS=thoreau-walden.txt

pip2.7 install -r scripts/requirements.txt

# Clean the corpus from non alpha-numeric symbols
scripts/clean_corpus.sh $CORPUS > $CORPUS.clean
echo "cleaned corpus"

# A) Window size 2 with "clean" subsampling
mkdir w2.sub
python2.7 scripts/corpus2pairs.py --win 2 --sub 1e-5 --pos --thr 1 $CORPUS.clean > w2.sub/pairs
echo "Made pairs file"
bash scripts/pairs2counts.sh w2.sub/pairs > w2.sub/counts
echo "Made counts file"
python scripts/pairs2relations.py w2.sub/pairs > w2.sub/relations
echo "Made relations file"
python2.7 scripts/counts2vocab.py w2.sub/counts
`
I get the following error: 

`
Requirement already satisfied: docopt in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 1))
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 2))
Requirement already satisfied: numpy>=1.7.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from scipy->-r scripts/requirements.txt (line 2))
cleaned corpus
mkdir: w2.sub: File exists
Traceback (most recent call last):
  File "scripts/corpus2pairs.py", line 5, in <module>
    from docopt import docopt
ImportError: No module named docopt
Made pairs file
Made counts file
Made relations file
Traceback (most recent call last):
  File "scripts/counts2vocab.py", line 3, in <module>
    from docopt import docopt
ImportError: No module named docopt
`

Do you have any idea why this might be?

**Comment by azpoliak** [comment]
That's a bit weird, what happens if you run "import docopt" in a simple
python interpreter?

**Comment by adamlauretig** [comment]
Looks like it was an error on my end. my apologies. I corrected 2.7 to 2.

**Comment by adamlauretig** [comment]
I did have to correct one thing, in `pairs2relations.py`,  I replaced

`for line in f.readlines():
  print(line.strip() + ' ' + str(int(random.random() * 1)))
  print(line.strip() + '_REL1')
`

with 
`for line in f.readlines():
  print(str(line.strip()) + ' ' + str(int(random.random() * 1)))
  print(str(line.strip()) + '_REL1')`

**Comment by adamlauretig** [comment]
(apologies for the nasty formatting)

**Comment by azpoliak** [comment]
No need to apologize. Happy to hear that you got it working! Feel free to make a merge request with that edit and I'd be happy to accept it. 

In this codebase, we only enable factorizing a _3_-dimensional tensor. In follow up [work](http://aclweb.org/anthology/S/S17/S17-1011.pdf) we extended the code here to enable creating word embeddings from _n_-dimensional tensors. If you are interested in that, you might want to checkout https://github.com/fmof/tensor-factorization
